name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/my-dotnet-webapi/my-dotnet-webapi.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/my-dotnet-webapi/my-dotnet-webapi.csproj

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal src/my-dotnet-webapi/my-dotnet-webapi.csproj

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          ci: true
          extra_plugins: |
            semantic-release/commit-analyzer
            semantic-release/release-notes-generator
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
